FROM python:latest
MAINTAINER Fabio Oliveira <blackjackdevel@gmail.com>
RUN pip3 install elasticsearch==2.1.0
RUN pip3 install flask==0.10.1
RUN pip3 install pika==0.10.0
RUN pip3 install requests==2.9.1
RUN pip3 install Flask-PyMongo==0.4.0
RUN pip3 install pymongo==3.1
RUN pip3 install cerberus==0.9.2
RUN pip3 install bcrypt==2.0.0
RUN pip3 install flask-cors==2.1.2
RUN pip3 install flask-socketio==2.1